
# things not included
# language
# notifications - no email notifications set up

name: pytest
on:
  pull_request:
    branches:
    - '*'

jobs:
  test_suite:
    name: Pytest on ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.7]
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0} 
    env:
      DESC: "Python 3.7 tests"  # is this even necessary ?
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "100"
      - name: setup-conda
        # You may pin to the exact commit or the version.
        # uses: s-weigand/setup-conda@bf65a211e008297225b737b153801ac1231e9758
        uses: s-weigand/setup-conda@v1.0.5
        with:
          # If conda should be updated before running other commands (Default: 'false')
          update-conda: true
          # Python version which should be installed with conda (default: 'Default')
          python-version: 3.7
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: pyviz/label/dev
