
# things not included
# language
# notifications - no email notifications set up

name: pytest
on:
  pull_request:
    branches:
    - '*'

jobs:
  test_suite:
    name: Pytest on ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.7]
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0} 
    env:
      DESC: "dev test_all"
      PYTHON_VERSION: ${{ matrix.python-version }}
      DISPLAY: ":99.0"
      CHANS_DEV: "-c pyviz/label/dev -c bokeh/label/dev -c conda-forge"
      CHANS_REL: "-c pyviz -c bokeh -c conda-forge"
      LABELS_DEV: "--label dev"
      LABELS_REL: "--label dev --label main"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${PYTHON_VERSON}
